/**
 * Application Constants
 */

const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  DISTRICT_COORDINATOR: 'DISTRICT_COORDINATOR',
  COORDINATOR: 'COORDINATOR',
  FIELD_MANAGER: 'FIELD_MANAGER',
  TEAM_LEADER: 'TEAM_LEADER',
  FIELD_EMPLOYEE: 'FIELD_EMPLOYEE',
  STUDENT: 'STUDENT'
};

const USER_HIERARCHY = {
  [USER_ROLES.SUPER_ADMIN]: {
    canCreate: [
      USER_ROLES.ADMIN,
      USER_ROLES.DISTRICT_COORDINATOR,
      USER_ROLES.COORDINATOR,
      USER_ROLES.FIELD_MANAGER,
      USER_ROLES.TEAM_LEADER,
      USER_ROLES.FIELD_EMPLOYEE
    ],
    canView: [
      USER_ROLES.SUPER_ADMIN,
      USER_ROLES.ADMIN,
      USER_ROLES.DISTRICT_COORDINATOR,
      USER_ROLES.COORDINATOR,
      USER_ROLES.FIELD_MANAGER,
      USER_ROLES.TEAM_LEADER,
      USER_ROLES.FIELD_EMPLOYEE
    ]
  },
  [USER_ROLES.ADMIN]: {
    canCreate: [
      USER_ROLES.DISTRICT_COORDINATOR,
      USER_ROLES.COORDINATOR,
      USER_ROLES.FIELD_MANAGER,
      USER_ROLES.TEAM_LEADER,
      USER_ROLES.FIELD_EMPLOYEE
    ],
    canView: [
      USER_ROLES.DISTRICT_COORDINATOR,
      USER_ROLES.COORDINATOR,
      USER_ROLES.FIELD_MANAGER,
      USER_ROLES.TEAM_LEADER,
      USER_ROLES.FIELD_EMPLOYEE
    ]
  },
  [USER_ROLES.DISTRICT_COORDINATOR]: {
    canCreate: [USER_ROLES.COORDINATOR, USER_ROLES.TEAM_LEADER],
    canView: [
      USER_ROLES.COORDINATOR,
      USER_ROLES.FIELD_MANAGER,
      USER_ROLES.TEAM_LEADER,
      USER_ROLES.FIELD_EMPLOYEE
    ]
  },
  [USER_ROLES.COORDINATOR]: {
    canCreate: [USER_ROLES.FIELD_MANAGER],
    canView: [
      USER_ROLES.FIELD_MANAGER,
      USER_ROLES.TEAM_LEADER,
      USER_ROLES.FIELD_EMPLOYEE
    ]
  },
  [USER_ROLES.FIELD_MANAGER]: {
    canCreate: [USER_ROLES.TEAM_LEADER],
    canView: [USER_ROLES.TEAM_LEADER, USER_ROLES.FIELD_EMPLOYEE]
  },
  [USER_ROLES.TEAM_LEADER]: {
    canCreate: [USER_ROLES.FIELD_EMPLOYEE],
    canView: [USER_ROLES.FIELD_EMPLOYEE]
  },
  [USER_ROLES.FIELD_EMPLOYEE]: {
    canCreate: [],
    canView: []
  }
};

module.exports = {
  USER_ROLES,
  USER_HIERARCHY
};

